version: "3.2"
services:
    portainer:
      image: portainer/portainer:latest
      command: -H unix:///var/run/docker.sock
      ports:
        - 9000:9000
      volumes:
        - portainer_data:/data
        - /var/run/docker.sock:/var/run/docker.sock
      deploy:
        placement:
          constraints: [node.role == manager]
        restart_policy:
          condition: on-failure
volumes:
  portainer_data:
    external: true
