version: "3.2"
services:
  db:
    image: r1group/restservices-mysql
    volumes:
      - restservices-db-data:/var/lib/mysql
    networks:
      - restservices
    secrets:
      - restservices-mysql_root_password
    deploy:
      restart_policy:
        condition: on-failure
  api:
    image: r1group/restservices-api
    environment:
      - NODE_ENV=prod
    networks:
      - restservices
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=api.common.r1group.co
        - com.df.servicePath=/
        - com.df.port=3000
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
volumes:
  restservices-db-data:
    external: true
networks:
  restservices:
    external: true
