version: "3.2"
services:
  mysql:
    image: mysql:5.7
    secrets:
      - autoglobal-mysql-root-password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/autoglobal-mysql-root-password
    volumes: 
      - autoglobal-db-data:/var/lib/mysql
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
  web:
    image: r1group/autoglobal-web-img:1.0.0
    volumes:
      - autoglobal-wp-html:/var/www/html
      - autoglobal-wp-uploads:/var/www/html/wp-content/uploads
    networks:
      - backend
      - proxy
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=www.autoglobal.com.ar,autoglobal.com.ar
        - com.df.servicePath=/
        - com.df.port=80
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  api:
    image: r1group/autoglobal-api-img:1.0.0
    volumes:
      - autoglobal-wp-uploads:/usr/app/common/models/imagenesQuiter
    networks:
      - backend
      - proxy
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=api.autoglobal.com.ar
        - com.df.servicePath=/
        - com.df.port=3333
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
secrets:
  autoglobal-mysql-root-password:
    external: true
volumes:
  autoglobal-db-data:
    external: true
  autoglobal-wp-html:
    external: true
  autoglobal-wp-uploads:
    external: true
networks:
  backend:
    external: false
  proxy:
    external: true