version: "3.2"
services:
  db:
    image: mysql:5.7
    volumes: 
      - autoglobal-db-data:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=Lorenzo911$$
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  autoglobal-db-data:
    external: true
networks:
  backend:
    external: false