version: "3.2"
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Lorenzo911$$
    volumes: 
      - autoglobal-db-data:/var/lib/mysql
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
  web:
    image: r1group/autoglobal-web-img:1.0.0
    volumes:
      - autoglobal-wp-html:/var/www/html
      - autoglobal-wp-uploads:/var/www/html/wp-content/uploads
    networks:
      - backend
      - proxy
    ports:
      - 80:80
  api:
    image: r1group/autoglobal-api-img:1.0.0
    volumes:
      - autoglobal-wp-uploads:/usr/app/common/models/imagenesQuiter
    networks:
      - backend
      - proxy
    ports:
      - 3333:3333
volumes:
  autoglobal-db-data:
    external: true
  autoglobal-wp-html:
    external: true
  autoglobal-wp-uploads:
    external: true
networks:
  backend:
    external: false
  proxy:
    external: true