version: "3.2"
services:
  mysql:
    image: mysql:5.7
    secrets:
      - gestra-mysql-root-password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/gestra-mysql-root-password
    volumes: 
      - gestra-db-data:/var/lib/mysql
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
secrets:
  gestra-mysql-root-password:
    external: true
volumes:
  gestra-db-data:
    external: true
networks:
  backend:
    external: false
